name: Render

on:
  workflow_dispatch:


jobs:
  build_0:
    name: wradlib notebooks - linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      WRADLIB_DATA: ./wradlib-data
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install micromamba
      run: |
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
        mv "$HOME/.bashrc" .bashrcBAK
        touch "$HOME/.bashrc"
        ./micromamba shell init -s bash -p ~/micromamba
        cat "$HOME/.bashrc" >> "$HOME/.bash_profile"
        mv .bashrcBAK "$HOME/.bashrc"
    - name: Install deps
      run: |
        micromamba create -y -n wradlib-tests python=${{ matrix.python-version }} -f ci/requirements/notebooks.txt --channel conda-forge
        echo "set -eo pipefail" >> "$HOME/.bash_profile"
        echo "micromamba activate wradlib-tests" >> "$HOME/.bash_profile"
    - name: Install wradlib
      run: |
        git clone https://github.com/wradlib/wradlib.git
        cd wradlib
        echo "WRADLIB_TAG=`git name-rev --name-only --tags HEAD`" >> $GITHUB_ENV
        python setup.py sdist
        python -m pip install . --no-deps
    - name: Clone wradlib-data
      run: |
        git clone https://github.com/wradlib/wradlib-data.git
    - name: Version Info
      run: |
        micromamba list
        python -c "import wradlib; print(wradlib.version.full_version)"
        python -c "import wradlib; print(wradlib.show_versions())"
    - name: Render with pytest
      env:
        WRADLIB_EARTHDATA_USER: ${{ secrets.WRADLIB_EARTHDATA_USER }}
        WRADLIB_EARTHDATA_PASS: ${{ secrets.WRADLIB_EARTHDATA_PASS }}
      run: |
        export WRADLIB_DATA=`realpath $WRADLIB_DATA`
        pytest -n auto --verbose --durations=15 --pyargs notebooks
    - name: Commit files
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --global user.email "wradlib-docs@wradlib.org"
        git config --global user.name "wradlib-docs-bot"
        git checkout --orphan render
        git add --all .
        git commit -m "Rendering at commit $GITHUB_SHA"
    - name: Push changes
      if: github.event_name == 'workflow_dispatch'
      run: |
        if [ $WRADLIB_TAG == 'undefined' ]; then
            BRANCH=devel
        else
            BRANCH=$WRADLIB_TAG
        fi
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/wradlib/wradlib-notebooks.git render:$BRANCH -fq

  trigger_rtd:
    if: github.event_name == 'workflow_dispatch'
    needs: [build_0]
    name: trigger readthedocs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
      RTD_URL: ${{ secrets.RTD_URL }}
    steps:
    - name: trigger readthedocs
      run: |
        curl -X POST -d "token=$RTD_TOKEN" "$RTD_URL"
